# This is a basic workflow to help you get started with Actions

name: hola mundo

# Controls when the workflow will run
on: [push]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
            
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
            
        with:
          node-version: '20'  # Puedes cambiar esto a la versión que necesites

      - name: Define variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

      - name: Run script
        run: node main.js
