name: Hola Mundo con GitHub Actions
run-name: ¡Estoy usando GitHub Actions!

on: [push]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Nombre de Usuario
        run:  echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Nombre del Workflow
        run:  echo "WORKFLOW=${{ github.workflow }}" >> $GITHUB_ENV
      - name: Script Corriendo
        run: node hola-mundo.js
